repos: #ruff's official pre-commit repo.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9 #without pinning ruff version, hooks would drift over time
    hooks:
      - id: ruff #same as ruff check --fix
        args: [--fix]
      - id: ruff-format #same as ruff format
