#!/bin/bash
# ============================================================================
# Setup Script
# ============================================================================
# Run after `terraform apply` to populate Airflow .env from Terraform outputs.
# Reads from the EPHEMERAL stack, which re-exports persistent values too,
# so one `terraform output` call yields everything the pipeline needs.
#
# Usage: ./scripts/setup_env.sh
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
TERRAFORM_DIR="$PROJECT_DIR/terraform/ephemeral"
AIRFLOW_DIR="$PROJECT_DIR/airflow"
ENV_FILE="$AIRFLOW_DIR/.env"

echo "🔧 Generating Airflow .env from Terraform outputs (ephemeral stack)..."
echo ""

if [ ! -d "$TERRAFORM_DIR/.terraform" ]; then
    echo "❌ Ephemeral stack not initialized. Run: cd terraform/ephemeral && terraform init"
    exit 1
fi

cd "$TERRAFORM_DIR"
OUTPUTS=$(terraform output -json 2>/dev/null)

if [ -z "$OUTPUTS" ] || [ "$OUTPUTS" == "{}" ]; then
    echo "❌ No Terraform outputs found. Run: cd terraform/ephemeral && terraform apply"
    exit 1
fi

get() { echo "$OUTPUTS" | python3 -c "import sys, json; print(json.load(sys.stdin)['$1']['value'])"; }

DATA_LAKE_ROOT=$(get data_lake_root)

cat > "$ENV_FILE" << ENVEOF
# Auto-generated by scripts/setup_env.sh on $(date)
# Do not edit manually — re-run the script after terraform apply.

DATA_LAKE_ROOT=${DATA_LAKE_ROOT}
SCRIPTS_LOCATION=s3://nateeatsrice-master-s3/scripts/data-pipeline
EMR_APP_ID=$(get emr_serverless_app_id)
EMR_EXECUTION_ROLE_ARN=$(get emr_execution_role_arn)
PIPELINE_RUNNER_ROLE_ARN=$(get pipeline_runner_role_arn)
GLUE_DB_BRONZE=$(get glue_database_bronze)
GLUE_DB_SILVER=$(get glue_database_silver)
GLUE_DB_GOLD=$(get glue_database_gold)
ATHENA_WORKGROUP=$(get athena_workgroup)
AWS_REGION=$(get aws_region)
ENVEOF

echo "✅ Airflow .env written to: $ENV_FILE"
echo ""
echo "Contents:"
echo "─────────"
cat "$ENV_FILE"
echo ""
echo "Next steps:"
echo "  1. make deploy-scripts   # upload PySpark scripts to the master bucket"
echo "  2. cd airflow && docker compose up -d"
echo "  3. Open http://localhost:8080 (admin/admin)"
